apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-test-app
  labels:
    app: devsecops-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-test-app
  template:
    metadata:
      labels:
        app: devsecops-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.1
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - name: devsecops-root-dir
            mountPath: /var/www/devsecops
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: devsecops-root-dir
          emptyDir: {}
